### ISSUE TITLE
Seems to alter EasyScreenCast

### ISSUE THREAD

**Issue by benintech** [trifonovkv/ReminderAlarmClock#22]
Using Debian 11 / GS 3.38 here.

This extension alters strangely the EasyScreenCast extension :

- EasyScreenCast without Reminder Alarm Clock
![easyscreencast_idle_no-reminder-alarm-clock](https://user-images.githubusercontent.com/5140169/179731684-9eb6791f-c26b-44c6-abf3-ce69dbd3f9a5.png)
![easyscreencast_recording_no-reminder-alarm-clock](https://user-images.githubusercontent.com/5140169/179731816-dec25cbb-2141-4dbd-adc5-c68248f09562.png)

- EasyScreenCast with Reminder Alarm Clock 
![easyscreencast_idle_reminder-alarm-clock](https://user-images.githubusercontent.com/5140169/179731921-715fffa0-1f3d-493d-af58-523efc599d6e.png)
![easyscreencast_recording_reminder-alarm-clock](https://user-images.githubusercontent.com/5140169/179731969-1c41a633-dcb2-4588-a81b-c9de5c8eef6f.png)

**Comment by nE0sIghT** [comment]
This is because both extensions uses same css class `time-label`.  

- https://github.com/EasyScreenCast/EasyScreenCast/blob/master/extension.js#L120
- https://github.com/trifonovkv/ReminderAlarmClock/blob/master/extension.js#L51

It's not exactly `our` bug, but incompatibility. I will prefix our css classes.
